package tugas10oop;
import javax.swing.table.DefaultTableModel;
public class FormDosen extends javax.swing.JFrame {
    
    
    
    public void tampilData() {
        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        dtm.setRowCount(0);
        for (int i = 0; i < Data.dsn.size(); i++) {

            DefaultTableModel tablemodel = (DefaultTableModel) jTable2.getModel();

            String nama = Data.dsn.get(i).getNama();
            String NIP = Data.dsn.get(i).getNIP();
            String prodi = Data.dsn.get(i).getProdi();
            String fakultas = Data.dsn.get(i).getFakultas();

            Object[] data = {NIP, nama, prodi, fakultas};

            tablemodel.addRow(data);
        }
    }

    public void tambahData() {
        String NIP = TextBoxNIPDosen.getText();
        String nama = TextBoxNamaDosen.getText();
        String prodi = TextBoxProdiDosen.getText();
        String fakultas = TextBoxFakultasDosen.getText();

        Dosen a = new Dosen(NIP, nama, prodi, fakultas);
        Data.dsn.add(a);
        
        Data.simpanDosen();
        tampilData();
    }

    public void edit() {
        TextBoxNIPDosen.setText(Data.dsn.get(jTable2.getSelectedRow()).getNIP());
        TextBoxNamaDosen.setText(Data.dsn.get(jTable2.getSelectedRow()).getNama());
        TextBoxProdiDosen.setText(Data.dsn.get(jTable2.getSelectedRow()).getProdi());
        TextBoxFakultasDosen.setText(Data.dsn.get(jTable2.getSelectedRow()).getFakultas());
    }

    public void updateData() {
        Data.dsn.get(jTable2.getSelectedRow()).setNIP(TextBoxNIPDosen.getText());
        Data.dsn.get(jTable2.getSelectedRow()).setNama(TextBoxNamaDosen.getText());
        Data.dsn.get(jTable2.getSelectedRow()).setProdi(TextBoxProdiDosen.getText());
        Data.dsn.get(jTable2.getSelectedRow()).setFakultas(TextBoxFakultasDosen.getText());
        Data.simpanDosen();
        tampilData();
    }

    public void hapusData() {
        try{
        Data.dsn.remove(jTable2.getSelectedRow());
        Data.simpanDosen();
        tampilData();
        }catch(java.lang.ArrayIndexOutOfBoundsException ex){
            
        }
    }

    public void reset() {
        TextBoxNIPDosen.setText("");
        TextBoxNamaDosen.setText("");
        TextBoxProdiDosen.setText("");
        TextBoxFakultasDosen.setText("");
    }

    /**
     * Creates new form FormDosen
     */
    public FormDosen() {
        initComponents();
        Data.initDosen();
        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        dtm.setRowCount(0);
        if (dtm.getRowCount() != 0){
            return;
        }else{
        tampilData();}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TextBoxNIPDosen = new javax.swing.JTextField();
        TextBoxNamaDosen = new javax.swing.JTextField();
        TextBoxProdiDosen = new javax.swing.JTextField();
        TextBoxFakultasDosen = new javax.swing.JTextField();
        ButtonTambahDosen = new javax.swing.JButton();
        ButtonUpdateDosen = new javax.swing.JButton();
        buttonHapusDosen = new javax.swing.JButton();
        buttonResetDosen = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Civitas Dosen");

        jLabel2.setText("NIP");

        jLabel3.setText("Nama");

        jLabel4.setText("Prodi");

        jLabel5.setText("Fakultas");

        TextBoxNIPDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextBoxNIPDosenActionPerformed(evt);
            }
        });

        ButtonTambahDosen.setText("Tambah");
        ButtonTambahDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTambahDosenActionPerformed(evt);
            }
        });

        ButtonUpdateDosen.setText("update");
        ButtonUpdateDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonUpdateDosenActionPerformed(evt);
            }
        });

        buttonHapusDosen.setText("hapus");
        buttonHapusDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusDosenActionPerformed(evt);
            }
        });

        buttonResetDosen.setText("Reset");
        buttonResetDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetDosenActionPerformed(evt);
            }
        });

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIM", "Nama", "Prodi", "Fakultas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setColumnSelectionAllowed(true);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonTambahDosen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonUpdateDosen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonHapusDosen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonResetDosen))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextBoxNIPDosen)
                                    .addComponent(TextBoxNamaDosen)
                                    .addComponent(TextBoxProdiDosen)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(TextBoxFakultasDosen)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TextBoxNIPDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextBoxNamaDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TextBoxProdiDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextBoxFakultasDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonTambahDosen)
                    .addComponent(ButtonUpdateDosen)
                    .addComponent(buttonHapusDosen)
                    .addComponent(buttonResetDosen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonTambahDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTambahDosenActionPerformed
        // TODO add your handling code here:
        tambahData();
    }//GEN-LAST:event_ButtonTambahDosenActionPerformed

    private void ButtonUpdateDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonUpdateDosenActionPerformed
        // TODO add your handling code here:
        updateData();
    }//GEN-LAST:event_ButtonUpdateDosenActionPerformed

    private void buttonHapusDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusDosenActionPerformed
        // TODO add your handling code here:
        hapusData();
    }//GEN-LAST:event_buttonHapusDosenActionPerformed

    private void buttonResetDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetDosenActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_buttonResetDosenActionPerformed

    private void TextBoxNIPDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextBoxNIPDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextBoxNIPDosenActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Tugas10OOP.mainForm.setVisible(true);
        Tugas10OOP.formDosen.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        edit();
    }//GEN-LAST:event_jTable2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDosen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonTambahDosen;
    private javax.swing.JButton ButtonUpdateDosen;
    private javax.swing.JTextField TextBoxFakultasDosen;
    private javax.swing.JTextField TextBoxNIPDosen;
    private javax.swing.JTextField TextBoxNamaDosen;
    private javax.swing.JTextField TextBoxProdiDosen;
    private javax.swing.JButton buttonHapusDosen;
    private javax.swing.JButton buttonResetDosen;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
